/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AgendamentoModel;
import model.ClienteModel;
import model.ServicoModel;
import model.ServicosAgendamentoModel;
import repository.AgendamentoRepository;
import repository.ClienteRepository;
import repository.ServicosAgendamentoRepository;
import repository.ServicosRepository;
import utils.Mascaras;
import utils.Utils;

/**
 *
 * @author skate
 */
public class JFrameAgendamento extends javax.swing.JFrame {
    List<ClienteModel> listClientes;
    List<ServicoModel> listServicos, listServicosSelecionados, listServicosEdicao;
    private Long codigo;
    AgendamentoRepository repository;
    ServicosAgendamentoRepository servicoAgendamentoRepository;
    AgendamentoModel agendamento;
    /**
     * Creates new form JFrame
     */
    public JFrameAgendamento() {
        initComponents();
        repository = new AgendamentoRepository();
        servicoAgendamentoRepository = new ServicosAgendamentoRepository();
        listServicosSelecionados = new ArrayList<>();
        this.preencheClientes();
        this.preencheServicos();
        this.preencheConsulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abasPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        campoDataHoraAgenda = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        comboServico = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServicosAgendamento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        campoHora = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        btnGravar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setTitle("Agendamento");
        setResizable(false);

        abasPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        abasPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Nome Cliente");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 153, 204));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Data");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel2.setOpaque(true);

        campoDataHoraAgenda.setFormats("dd/MM/yyyy");

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Serviço");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel3.setOpaque(true);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaServicosAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serviço"
            }
        ));
        tabelaServicosAgendamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaServicosAgendamentoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaServicosAgendamento);

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Hora");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel4.setOpaque(true);

        try {
            campoHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("SELECIONE O SERVIÇO E PRESSIONE [DELETE] PARA EXCLUIR O SERVIÇO DA LISTA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoDataHoraAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboServico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(comboCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(campoDataHoraAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(campoHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboServico, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        abasPanel.addTab("Agendar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseClicked(evt);
            }
        });
        tabelaConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaConsultaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaConsulta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        abasPanel.addTab("Consulta", jPanel3);

        btnGravar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setEnabled(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasPanel)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(abasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(989, 880));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaConsultaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           this.preencherCampos();
        }
    }//GEN-LAST:event_tabelaConsultaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listServicosSelecionados.add(listServicos.stream().filter(s -> s.getDescricao().equals(comboServico.getSelectedItem().toString())).findFirst().get());
        this.preencherTabelaServico();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaServicosAgendamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaServicosAgendamentoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o serviço do agendamento?","Galera de casa aí, comé que é, meu",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(dialogResult == JOptionPane.YES_OPTION){
                System.out.println("ID Serv: "+tabelaServicosAgendamento.getValueAt(tabelaServicosAgendamento.getSelectedRow(), 0).toString());
                listServicosSelecionados.removeIf((s -> s.getId().equals(Long.parseLong(tabelaServicosAgendamento.getValueAt(tabelaServicosAgendamento.getSelectedRow(), 0).toString()))));
                this.preencherTabelaServico();
            }
        }
    }//GEN-LAST:event_tabelaServicosAgendamentoKeyReleased

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            this.buildAgendamento();
        
            if(codigo != null){
                agendamento.setId(codigo);
                this.repository.alterarAgendamento(agendamento);
                if(listServicosEdicao!= null && !listServicosEdicao.isEmpty()){
                    List<ServicoModel> servicosRemovidos = listServicosEdicao.stream().filter(e -> (listServicosSelecionados.stream().filter(d -> d.getId().equals(e.getId())).count())<1).collect(Collectors.toList());
                    List<ServicoModel> servicosAdicionados = listServicosSelecionados.stream().filter(e -> (listServicosEdicao.stream().filter(d -> d.getId().equals(e.getId())).count())<1).collect(Collectors.toList());
                    
                    servicosRemovidos.forEach(servico -> {
                    try {
                        servicoAgendamentoRepository.delete(ServicosAgendamentoModel.builder()
                                .agendamento(agendamento)
                                .servico(servico)
                                .build());
                    } catch (SQLException ex) {
                        Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    });
                    servicosAdicionados.forEach(servico -> {
                        try {
                            servicoAgendamentoRepository.save(ServicosAgendamentoModel.builder()
                                    .agendamento(agendamento)
                                    .servico(servico)
                                    .build());
                        } catch (SQLException ex) {
                            Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    });
                } else {
                    listServicosSelecionados.forEach((servicoSelecionado) -> {
                        try {
                            servicoAgendamentoRepository.save(ServicosAgendamentoModel.builder()
                                    .agendamento(agendamento)
                                    .servico(servicoSelecionado)
                                    .build());
                        } catch (SQLException ex) {
                            Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    });
                }
            } else {
                agendamento = this.repository.agendar(agendamento);
                listServicosSelecionados.forEach((servicoSelecionado) -> {
                    try {
                        servicoAgendamentoRepository.save(ServicosAgendamentoModel.builder()
                                .agendamento(agendamento)
                                .servico(servicoSelecionado)
                                .build());
                    } catch (SQLException ex) {
                        Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
                    }
                });
            }
            this.preencheConsulta();
            btnNovo.setEnabled(true);
            btnExcluir.setEnabled(true);
            
            JOptionPane.showMessageDialog(this, "Agendamento salvo com sucesso!", "Quem sabe faz ao vivo!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao tentar salvar o Cliente", "Errrrôôôuuuu!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o agendamento?","Galera de casa aí, comé que é, meu?",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(dialogResult == JOptionPane.YES_OPTION){
            try {
                repository.delete(agendamento);
                this.limparCampos();
                this.preencheConsulta();
                listServicosSelecionados = new ArrayList<>();
                this.preencherTabelaServico();
                JOptionPane.showMessageDialog(this, "Agendamento excluído com sucesso!", "Quem sabe faz ao vivo!", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao tentar excluir o Agendamento", "Errrrôôôuuuu!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseClicked
        if(evt.getClickCount() == 2){
            this.preencherCampos();
        }
    }//GEN-LAST:event_tabelaConsultaMouseClicked

    private void preencheClientes(){
        ClienteRepository clienteRepository = new ClienteRepository();
        try {
            listClientes = clienteRepository.findAllCombo();
            comboCliente.addItem("...");
            listClientes.forEach((clienteUnique) -> {
                comboCliente.addItem(clienteUnique.getNome());
             });
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
    private void preencheServicos(){
        ServicosRepository servicoRepository = new ServicosRepository();
        try {
            listServicos = servicoRepository.findAll();
            comboServico.addItem("...");
            listServicos.forEach((servicoUnique) -> {
                comboServico.addItem(servicoUnique.getDescricao());
             });
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
    private void preencherTabelaServico(){
        DefaultTableModel model = new DefaultTableModel(
            new Object[][] { },
            //aqui a construçao do cabeçalho        
            new String [] {"","Descrição","Valor"}){
                Class[] types = new Class[]{
                //para cada coluna acrescentar mais um construtor
                    java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,
        };
        //para cada coluna acrescentar mais um objetooo...
        boolean[] canEdit = new boolean[] {false,false,false};
    
        public Class getColumnClass(int columnIndex){
            return types[columnIndex];
        }
        public boolean isCellEditable(int rowIndex,int columnIndex){
            return canEdit[columnIndex];
        }  
        };
    //construçao do conteudo da tabela........................
    //usando o BD 
    listServicosSelecionados.forEach((servicoSelecionado) -> {
        model.addRow(new Object[]{servicoSelecionado.getId(), servicoSelecionado.getDescricao(),Mascaras.monetario.format(servicoSelecionado.getValor())});
    });
     
     tabelaServicosAgendamento.setModel(model);
     tabelaServicosAgendamento.sizeColumnsToFit(10);
     tabelaServicosAgendamento.setRowHeight(20);
     tabelaServicosAgendamento.getColumnModel().getColumn(0).setResizable(false);
     tabelaServicosAgendamento.getColumnModel().getColumn(0).setPreferredWidth(0);
     tabelaServicosAgendamento.getColumnModel().getColumn(0).setMaxWidth(0);
     tabelaServicosAgendamento.getColumnModel().getColumn(0).setMinWidth(0);;
     tabelaServicosAgendamento.getColumnModel().getColumn(1).setResizable(false);
     tabelaServicosAgendamento.getColumnModel().getColumn(1).setPreferredWidth(200);
     tabelaServicosAgendamento.getColumnModel().getColumn(2).setResizable(false);
     tabelaServicosAgendamento.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
    private void buildAgendamento(){
        agendamento = AgendamentoModel.builder()
                .clienteModel(listClientes.get(comboCliente.getSelectedIndex()-1))
                .dataHora(utils.Utils.convetDateAndStringHourToLocalDateTime(campoDataHoraAgenda.getDate(), campoHora.getText()))
                .build();
    }
    
    private void limparCampos(){
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(true);
        listServicosSelecionados = new ArrayList<>();
        comboCliente.setSelectedIndex(0);
        comboServico.setSelectedIndex(0);
        campoDataHoraAgenda.setDate(null);
        campoHora.setText(null);
    }
    
    private void preencheConsulta(){
        DefaultTableModel model = new DefaultTableModel(
            new Object[][] { },
            //aqui a construçao do cabeçalho        
            new String [] {"","Cliente","Data"}){
                Class[] types = new Class[]{
                //para cada coluna acrescentar mais um construtor
                    java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,
        };
        //para cada coluna acrescentar mais um objetooo...
        boolean[] canEdit = new boolean[] {false,false,false};
    
        public Class getColumnClass(int columnIndex){
            return types[columnIndex];
        }
        public boolean isCellEditable(int rowIndex,int columnIndex){
            return canEdit[columnIndex];
        }  
        };
        try {
            repository.findAllAgendamentosFuturos().forEach((agendamentoUnique) -> {
                model.addRow(new Object[]{agendamentoUnique.getId(), agendamentoUnique.getClienteModel().getNome(),Utils.formatLocalDateTime(agendamentoUnique.getDataHora(), "dd/MM/yyyy HH:mm")});
            }); 
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     tabelaConsulta.setModel(model);
     tabelaConsulta.sizeColumnsToFit(10);
     tabelaConsulta.setRowHeight(20);
     tabelaConsulta.getColumnModel().getColumn(0).setResizable(false);
     tabelaConsulta.getColumnModel().getColumn(0).setPreferredWidth(0);
     tabelaConsulta.getColumnModel().getColumn(0).setMaxWidth(0);
     tabelaConsulta.getColumnModel().getColumn(0).setMinWidth(0);
     tabelaConsulta.getColumnModel().getColumn(1).setResizable(false);
     tabelaConsulta.getColumnModel().getColumn(1).setPreferredWidth(200);
     tabelaConsulta.getColumnModel().getColumn(2).setResizable(false);
     tabelaConsulta.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
    private void preencherCampos(){
        abasPanel.setSelectedIndex(0);
        codigo = Long.parseLong(tabelaConsulta.getValueAt(tabelaConsulta.getSelectedRow(), 0).toString());
        try {
            agendamento = repository.findOne(AgendamentoModel.builder().id(codigo).build());
            comboCliente.setSelectedItem(agendamento.getClienteModel().getNome());
            Date data = Utils.convertLocalDateTimeToDate(agendamento.getDataHora());
            campoDataHoraAgenda.setDate(data);
            int hora = data.getHours();
            int minuto = data.getMinutes();
            String horas = (hora < 10 ? "0"+String.valueOf(hora) : String.valueOf(hora));
            String minutos = (minuto < 10 ? "0"+String.valueOf(minuto) : String.valueOf(minuto));
            String horaCompleta = horas + ":" + minutos;
            campoHora.setText(horaCompleta);
            listServicosSelecionados = new ArrayList<>();
            servicoAgendamentoRepository.findServicosPorAgendamento(agendamento).forEach((servicoAgend) -> {
                listServicosSelecionados.add(servicoAgend.getServico());
            });
            listServicosEdicao = new ArrayList<>();
            listServicosEdicao.addAll(listServicosSelecionados);
            if(!listServicosSelecionados.isEmpty()){
                this.preencherTabelaServico();
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameAgendamento().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasPanel;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private org.jdesktop.swingx.JXDatePicker campoDataHoraAgenda;
    private javax.swing.JFormattedTextField campoHora;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaConsulta;
    private javax.swing.JTable tabelaServicosAgendamento;
    // End of variables declaration//GEN-END:variables
}
